(() => {
'use strict';
const D=window.ENERGY2027_DATA,C=window.ENERGY2027_CONFIG;
const state={orgId:'org_rn',tab:'overview',query:'',evidence:'all'};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
class DataStore{constructor(data){Object.assign(this,data);this.byId=new Map([...data.organizations,...data.actors,...data.sources].map(x=>[x.id,x]));} entity(id){return this.byId.get(id)} org(id){return this.organizations.find(x=>x.id===id)} relationsFor(id){return this.relations.filter(x=>x.fromId===id||x.toId===id)} relationsTo(id){return this.relations.filter(x=>x.toId===id)} claimsFor(id){return this.claims.filter(x=>x.subjectId===id)} positionsFor(id){return this.positions.filter(x=>x.holderId===id)} assessmentFor(id){return this.assessments.find(x=>x.holderId===id)} timelineFor(id){return this.timelines.find(x=>x.holderId===id)} sourcesFor(ids=[]){return ids.map(id=>this.sources.find(s=>s.id===id)).filter(Boolean)} validate(){const ids=new Set([...this.organizations,...this.actors,...this.sources].map(x=>x.id)),errors=[];for(const r of this.relations){if(!ids.has(r.fromId))errors.push(`Relation ${r.id}: fromId inconnu`);if(!ids.has(r.toId))errors.push(`Relation ${r.id}: toId inconnu`);for(const s of r.sourceIds||[])if(!ids.has(s))errors.push(`Relation ${r.id}: source inconnue ${s}`)}for(const c of this.claims){if(!ids.has(c.subjectId))errors.push(`Claim ${c.id}: sujet inconnu`);for(const s of c.sourceIds||[])if(!ids.has(s))errors.push(`Claim ${c.id}: source inconnue ${s}`)}return errors}}
const store=new DataStore(D);const validation=store.validate();if(validation.length)console.error('Erreurs de données',validation);else console.info('Énergie 2027 : données validées.');
const cls=v=>v>=75?'hi':v>=40?'mid':'lo';const evLabel=e=>(C.evidenceLevels.find(x=>x.id===e)||{}).label||'À documenter';
function setText(){const dt=new Date(D.meta.cutoff+'T00:00:00');const f=new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'long',year:'numeric'}).format(dt);$('#cutoff').textContent='État des informations : '+f;$('#footerCutoff').textContent=f;const k=[['orgs',D.organizations.length,'camps suivis'],['actors',D.actors.length,'acteurs / structures'],['claims',D.claims.length,'affirmations'],['sources',D.sources.length,'sources indexées']];$('#kpis').innerHTML=k.map(x=>`<div class="kpi"><strong>${x[1]}</strong><span>${esc(x[2])}</span></div>`).join('')}
function linkedActors(orgId){return store.relationsTo(orgId).map(r=>({actor:store.entity(r.fromId),rel:r})).filter(x=>x.actor)}
function renderPartyList(){const q=state.query.trim().toLowerCase();$('#partyList').innerHTML=D.organizations.filter(o=>{const names=linkedActors(o.id).map(x=>x.actor.name).join(' ');return !q||(o.name+' '+o.shortName+' '+o.candidateLabel+' '+names).toLowerCase().includes(q)}).map(o=>`<button class="party-btn ${o.id===state.orgId?'active':''}" data-pick="${o.id}"><i class="dot" style="background:${o.color}"></i><span><b>${esc(o.shortName)} · ${esc(o.name)}</b><small>${esc(o.candidateLabel)}</small></span></button>`).join('')||'<p>Aucun résultat.</p>'}
function renderOverview(){const o=store.org(state.orgId), pos=store.positionsFor(o.id);$('#v-overview').innerHTML=`<div class="party-head"><div class="party-head-top"><div><div class="eyebrow" style="color:${o.color}">${esc(o.shortName)}</div><h3>${esc(o.name)}</h3><p>${esc(o.summary)}</p></div><span class="status">${esc(o.status)}</span></div><div class="axes">${pos.slice(0,8).map(p=>{const c=C.criteria.find(x=>x.id===p.topicId);return `<div class="axis"><div class="axis-top"><span>${esc(c.label)}</span><b>${p.score}</b></div><div class="bar"><div class="fill" style="width:${p.score}%;background:${o.color}"></div></div></div>`}).join('')}</div></div><div class="two"><div class="mini"><h4>Chaîne de fabrication</h4><p>${esc(o.factory)}</p></div><div class="mini"><h4>Marqueurs doctrinaux</h4><ul>${o.markers.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div>`}
function filteredLinks(){return linkedActors(state.orgId).filter(x=>state.evidence==='all'||x.rel.evidenceLevel===state.evidence)}
function renderPeople(){const links=filteredLinks();$('#v-people').innerHTML=`<div class="people">${links.map(({actor,rel})=>`<button class="person" data-actor="${actor.id}"><span class="proof ${rel.evidenceLevel}">${rel.evidenceLevel==='U'?'?':rel.evidenceLevel}</span><span class="role">${esc(rel.roleLabel)}</span><h4>${esc(actor.name)}</h4><p>${esc(actor.description)}</p></button>`).join('')}</div>${links.length?'':'<p>Aucun acteur pour ce filtre.</p>'}`}
function renderClaims(){const allowed=new Set(filteredLinks().map(x=>x.actor.id));allowed.add(state.orgId);const cs=D.claims.filter(c=>allowed.has(c.subjectId)&&(state.evidence==='all'||c.evidenceLevel===state.evidence));$('#v-claims').innerHTML=`<div class="dissent">${cs.map((c,i)=>{const s=store.entity(c.subjectId);return `<div class="ditem"><b>${esc(s?.name||'Sujet')} · ${esc(evLabel(c.evidenceLevel))}</b><p>${esc(c.statement)}</p><small>${esc(c.certainty)} · ${esc(c.reviewStatus)}</small></div>`}).join('')}</div>${cs.length?'':'<p>Aucune affirmation pour ce filtre.</p>'}`}
function renderTimeline(){const t=store.timelineFor(state.orgId);$('#v-timeline').innerHTML=`<div class="timeline">${t.events.map(x=>`<div class="time"><strong>${esc(x.date)}</strong><p>${esc(x.label)}</p></div>`).join('')}</div>`}
function renderRte(){const a=store.assessmentFor(state.orgId);const src=store.sourcesFor(a.sourceIds);$('#v-rte').innerHTML=`<div class="rte"><div><div class="eyebrow">Confrontation analytique</div><h3>${esc(a.title)}</h3><div class="meter"><div style="width:${a.score}%"></div></div><p>${esc(a.summary)}</p><p><b>Indice de convergence : ${a.score}/100.</b> Ce n’est pas une note de RTE.</p></div><div><h3>Points à tester</h3><ul>${a.testPoints.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${src.map(s=>`<a class="ext" target="_blank" rel="noopener noreferrer" href="${esc(s.url)}">↗ ${esc(s.title)}</a>`).join('')}</div></div>`}
function renderNetwork(){const o=store.org(state.orgId), links=filteredLinks(), svg=$('#net'),cx=460,cy=270;let s='<defs><filter id="sh"><feDropShadow dx="0" dy="3" stdDeviation="4" flood-opacity=".12"/></filter></defs>';const n=links.length;links.forEach((x,i)=>{const a=-Math.PI/2+i*2*Math.PI/Math.max(1,n),px=cx+Math.cos(a)*300,py=cy+Math.sin(a)*190;s+=`<line x1="${cx}" y1="${cy}" x2="${px}" y2="${py}" stroke="#cbd0d6" stroke-width="2"/><text x="${(cx+px)/2}" y="${(cy+py)/2-5}" text-anchor="middle" font-size="9" fill="#667085">${esc(x.rel.roleLabel).slice(0,25)}</text>`});s+=`<g filter="url(#sh)"><rect x="365" y="229" rx="15" width="190" height="82" fill="${o.color}"/><text x="460" y="266" text-anchor="middle" font-size="15" font-weight="850" fill="#fff">${esc(o.shortName)}</text><text x="460" y="286" text-anchor="middle" font-size="10" fill="#fff">${esc(o.name).slice(0,32)}</text></g>`;links.forEach((x,i)=>{const a=-Math.PI/2+i*2*Math.PI/Math.max(1,n),px=cx+Math.cos(a)*300,py=cy+Math.sin(a)*190,nm=x.actor.name.length>24?x.actor.name.slice(0,23)+'…':x.actor.name;s+=`<g data-actor="${x.actor.id}" style="cursor:pointer" filter="url(#sh)"><rect x="${px-85}" y="${py-35}" rx="15" width="170" height="70" fill="#fff" stroke="#d8dde3"/><circle cx="${px+70}" cy="${py-21}" r="10" class="${x.rel.evidenceLevel}"/><text x="${px+70}" y="${py-17}" text-anchor="middle" font-size="10" font-weight="900" fill="#fff">${x.rel.evidenceLevel==='U'?'?':x.rel.evidenceLevel}</text><text x="${px}" y="${py-2}" text-anchor="middle" font-size="13" font-weight="850" fill="#1c293b">${esc(nm)}</text><text x="${px}" y="${py+17}" text-anchor="middle" font-size="9.5" fill="#6a7483">${esc(x.rel.roleLabel).slice(0,30)}</text></g>`});svg.innerHTML=s}
function renderAll(){renderPartyList();renderOverview();renderPeople();renderClaims();renderTimeline();renderRte();if(state.tab==='network')renderNetwork()}
function openActor(id){const a=store.entity(id),rels=store.relationsFor(id),claims=store.claimsFor(id),srcIds=[...new Set([...rels.flatMap(r=>r.sourceIds||[]),...claims.flatMap(c=>c.sourceIds||[])])],srcs=store.sourcesFor(srcIds),r=rels.find(x=>x.toId===state.orgId)||rels[0];$('#drawerBody').innerHTML=`<span class="badge">${esc(r?.roleLabel||a.type)}</span> <span class="badge">${esc(evLabel(r?.evidenceLevel||'U'))}</span><h3>${esc(a.name)}</h3><p class="lead">${esc(a.description)}</p><div class="detail"><h4>Relations</h4>${rels.map(x=>{const other=store.entity(x.fromId===id?x.toId:x.fromId);return `<p><b>${esc(x.roleLabel)}</b> avec ${esc(other?.name||'entité')} · preuve ${esc(x.evidenceLevel)} · ${esc(x.certainty)}</p>`}).join('')}</div><div class="detail"><h4>Affirmations liées</h4>${claims.map(c=>`<p>${esc(c.statement)} <small>(${esc(c.certainty)}, ${esc(c.reviewStatus)})</small></p>`).join('')||'<p>Aucune affirmation indexée.</p>'}</div><div class="detail"><h4>Sources liées</h4>${srcs.map(s=>`<a class="ext" target="_blank" rel="noopener noreferrer" href="${esc(s.url)}">↗ ${esc(s.title)}</a>`).join('')||'<p>Aucune source spécifique indexée.</p>'}</div>`;$('#drawer').classList.add('open');$('#overlay').classList.add('open');$('#drawer').setAttribute('aria-hidden','false')}
function closeDrawer(){$('#drawer').classList.remove('open');$('#overlay').classList.remove('open');$('#drawer').setAttribute('aria-hidden','true')}
function renderMatrix(){let h='<thead><tr><th>Camp</th>'+C.criteria.map(c=>`<th>${esc(c.label)}</th>`).join('')+'<th>RTE*</th></tr></thead><tbody>';for(const o of D.organizations){const map=new Map(store.positionsFor(o.id).map(p=>[p.topicId,p.score]));h+=`<tr><td><button class="btn ghost" data-pick="${o.id}" data-scroll="#atlas">${esc(o.shortName)}</button><br><small>${esc(o.name)}</small></td>${C.criteria.map(c=>{const v=map.get(c.id);return `<td class="${cls(v)}">${v}</td>`}).join('')}<td class="${cls(store.assessmentFor(o.id).score)}">${store.assessmentFor(o.id).score}</td></tr>`}$('#matrixTable').innerHTML=h+'</tbody>'}
function renderWatch(){$('#watchGrid').innerHTML=D.watch.map(w=>{const a=store.entity(w.actorId),o=store.org(w.organizationId);return `<button class="wcard" data-pick="${o.id}" data-actor="${a.id}"><div class="rank">#${w.rank}</div><small>${esc(o.shortName)}</small><h4>${esc(a.name)}</h4><p>${esc(w.reason)}</p></button>`}).join('')}
function renderSources(){$('#sourcesGrid').innerHTML=D.sources.map(s=>`<a class="card source" target="_blank" rel="noopener noreferrer" href="${esc(s.url)}"><b>${esc(s.title)}</b><span>${esc(s.summary)}</span><em>${esc(s.type)} · fiabilité ${esc(s.reliability)}</em></a>`).join('')}
function renderCriteria(){$('#criteria').innerHTML='<tbody>'+C.criteria.map(c=>`<tr><td>${esc(c.label)}</td><td>${esc(c.description)}</td></tr>`).join('')+'</tbody>'}
function dl(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportJSON(){dl(new Blob([JSON.stringify({config:C,data:D},null,2)],{type:'application/json'}),'energie2027-corpus-v2.json')}
function exportCSV(){const head=['camp','nom',...C.criteria.map(c=>c.label),'RTE'];const rows=[head,...D.organizations.map(o=>{const m=new Map(store.positionsFor(o.id).map(p=>[p.topicId,p.score]));return [o.shortName,o.name,...C.criteria.map(c=>m.get(c.id)),store.assessmentFor(o.id).score]})];const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\n');dl(new Blob([csv],{type:'text/csv;charset=utf-8'}),'energie2027-matrice.csv')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1600)}
document.addEventListener('click',e=>{const pick=e.target.closest('[data-pick]'),actor=e.target.closest('[data-actor]'),tab=e.target.closest('[data-tab]'),scroll=e.target.closest('[data-scroll]');if(pick){state.orgId=pick.dataset.pick;renderAll();toast(store.org(state.orgId).name)}if(actor)openActor(actor.dataset.actor);if(tab){state.tab=tab.dataset.tab;$$('.tab').forEach(b=>b.classList.toggle('active',b===tab));$$('.view').forEach(v=>v.classList.toggle('active',v.id==='v-'+state.tab));if(state.tab==='network')renderNetwork()}if(scroll)$(scroll.dataset.scroll)?.scrollIntoView({behavior:'smooth'})});
$('#search').addEventListener('input',e=>{state.query=e.target.value;renderPartyList()});$('#evidenceFilter').addEventListener('change',e=>{state.evidence=e.target.value;renderPeople();renderClaims();if(state.tab==='network')renderNetwork()});$('#overlay').addEventListener('click',closeDrawer);$('#closeDrawer').addEventListener('click',closeDrawer);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer()});$('#exportJson').addEventListener('click',exportJSON);$('#exportCsv').addEventListener('click',exportCSV);
setText();renderAll();renderMatrix();renderWatch();renderSources();renderCriteria();
})();
